# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast shows 🎭
docs: true
docsurl: https://radio-aktywne.github.io/emishows
email: it@radioaktywne.pl
envprefix: EMISHOWS
events: true
imagename: services/emishows
importname: emishows
port: 35000
registry: true
releases: true
reponame: emishows
repourl: https://github.com/radio-aktywne/emishows
servicename: emishows
sse: true
