# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast shows 🎭
docs: true
docsurl: https://radio-aktywne.github.io/beaver
email: it@radioaktywne.pl
envprefix: BEAVER
events: true
imagename: services/beaver
importname: beaver
port: 10500
registry: true
releases: true
reponame: beaver
repourl: https://github.com/radio-aktywne/beaver
servicename: beaver
sse: true
