# Generated by Django 4.0.8 on 2022-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Replay'), (3, 'Prerecorded')]),
        ),
    ]
